name: Build and Deploy Jekyll Site

on:
  push:
    branches:
      - main  # Adjust to your default branch
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Ruby with Bundler cache
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.7 # Adjust to match your Ruby version
          bundler-cache: true

      # Install dependencies
      - name: Install dependencies
        run: bundle install

      # Build the Jekyll site
      - name: Build Jekyll site
        run: bundle exec jekyll build

      # Optionally test the site with html-proofer
      - name: Test with html-proofer
        run: bundle exec htmlproofer ./_site
        env:
          HTML_PROOFER_OPTS: --assume-extension
